ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - less
  - typeit
publicHoistPattern:
  - pdfjs-dist
peerDependencyRules:
  allowedVersions:
    "tailwind-variants@3>tailwind-merge": "2"
